stages:
  - mirror
  - test
  - install
  - build
  - deploy
  - release
  - docstats
  - finalize

variables:
  GITLAB_ACCESS_TOKEN: "$GITLAB_ACCESS_TOKEN"
  GITHUB_OAUTH_TOKEN: "$GITHUB_OAUTH_TOKEN"

clone_master:
  stage: mirror
  only:
    - master
    - develop
  tags:
    - key_github
  script:
    - git checkout master
    - git pull origin master
    - git push -u git@github.com:namboy94/xdcc-downloader.git master --force
    - git checkout develop
    - git pull origin develop
    - git push -u git@github.com:namboy94/xdcc-downloader.git develop --force

run_unit_tests_python_2:
  stage: test
  tags:
    - linux
    - python
  script:
    - 3to2 . --write
    - python2 setup.py test

run_unit_tests_python_3_with_coverage:
  stage: test
  tags:
    - linux
    - python
  script:
    - python3 setup.py nosetests --with-coverage --cover-package=xdcc_dl --cover-branches --cover-erase --cover-html --cover-inclusive --nocapture -v
    - rsync -av cover/ /var/www/coverage.namibsun.net/public_html/xdcc-downloader --delete-before

run_unit_tests_windows:
  stage: test
  tags:
    - windows
    - python
  script:
    - python setup.py test

install_on_linux:
  stage: install
  only:
    - master
    - develop
  tags:
    - linux
    - python
  script:
    - python3 setup.py install --user

install_on_windows:
  stage: install
  only:
    - master
    - develop
  tags:
    - windows
    - python
  script:
    - python setup.py install

pyinstaller_linux:
  stage: build
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 setup.py install --user
    - python3 builder.py build pyinstaller_linux
    - pip3 uninstall xdcc_dl -y
  artifacts:
    paths:
      - build/gitlab_build_scripts/*

pyinstaller_windows:
  stage: build
  only:
    - master
  tags:
    - windows
    - python
  script:
    - python setup.py install
    - python builder.py build pyinstaller_windows
    - pip uninstall xdcc_dl -y
  artifacts:
    paths:
      - build/gitlab_build_scripts/*

source_dist:
  stage: deploy
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 setup.py register sdist upload

binary_3_dist:
  stage: deploy
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 setup.py bdist_wheel upload

binary_2_dist:
  stage: deploy
  only:
    - master
  tags:
    - python
    - linux
  script:
    - 3to2 . --write
    - python2 setup.py bdist_wheel
    - twine upload dist/*

upload_release_to_github:
  stage: release
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 builder.py github-release

upload_release_to_gitlab:
  stage: release
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 builder.py gitlab-release

generate_sphinx_documentation:
  stage: docstats
  only:
    - master
    - develop
  tags:
    - linux
    - python
  script:
    - cd doc
    - make buildsource
    - make latexpdf
    - make html
    - rsync -av build/latex/xdcc-downloader.pdf /var/www/docs.namibsun.net/public_html/pdf_docs/xdcc_downloader.pdf --delete-before
    - rsync -av build/html/ /var/www/docs.namibsun.net/public_html/html_docs/xdcc_downloader --delete-before
    - cd ..

gitstats:
  stage: docstats
  only:
    - master
    - develop
  tags:
    - linux
  script:
    - gitstats . gitstats
    - rsync -av gitstats/ /var/www/gitstats.namibsun.net/public_html/gitstats/xdcc_downloader --delete-before
    - git_stats generate
    - rsync -av git_stats/ /var/www/gitstats.namibsun.net/public_html/git_stats/xdcc_downloader --delete-before

update_html_pages:
  stage: finalize
  when: always
  script:
    - git clone https://gitlab.namibsun.net/namboy94/html-index-generator.git
    - python html-index-generator/html-index-generator.py /var/www/coverage.namibsun.net/public_html
      /var/www/coverage.namibsun.net/public_html/index.html
    - python html-index-generator/html-index-generator.py /var/www/docs.namibsun.net/public_html
      /var/www/docs.namibsun.net/public_html/index.html
    - python html-index-generator/html-index-generator.py /var/www/gitstats.namibsun.net/public_html
      /var/www/gitstats.namibsun.net/public_html/index.html