stages:
  - mirror

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
<<<<<<< HEAD
    - git push git@github.com:namboy94/jxdcc.git master -f
=======
    - git push git@github.com:namboy94/hexchat-downloader.git master -f
>>>>>>> hexchat-downloader/master
